In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/fifa23.csv')
df.head()

,Known As,Full Name,Overall,Potential,Value(in Euro),Positions Played,Best Position,Nationality,Image Link,Age,...,LM Rating,CM Rating,RM Rating,LWB Rating,CDM Rating,RWB Rating,LB Rating,CB Rating,RB Rating,GK Rating
0,L. Messi,Lionel Messi,91,91,54000000,RW,CAM,Argentina,https://cdn.sofifa.net/players/158/023/23_60.png,35,...,91,88,91,67,66,67,62,53,62,22
1,K. Benzema,Karim Benzema,91,91,64000000,"CF,ST",CF,France,https://cdn.sofifa.net/players/165/153/23_60.png,34,...,89,84,89,67,67,67,63,58,63,21
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,ST,Poland,https://cdn.sofifa.net/players/188/545/23_60.png,33,...,86,83,86,67,69,67,64,63,64,22
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,"CM,CAM",CM,Belgium,https://cdn.sofifa.net/players/192/985/23_60.png,31,...,91,91,91,82,82,82,78,72,78,24
4,K. Mbappé,Kylian Mbappé,91,95,190500000,"ST,LW",ST,France,https://cdn.sofifa.net/players/231/747/23_60.png,23,...,92,84,92,70,66,70,66,57,66,21

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18539 entries, 0 to 18538
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Known As                     18539 non-null  object
 1   Full Name                    18539 non-null  object
 2   Overall                      18539 non-null  int64
 3   Potential                    18539 non-null  int64
 4   Value(in Euro)               18539 non-null  int64
 5   Positions Played             18539 non-null  object
 6   Best Position                18539 non-null  object
 7   Nationality                  18539 non-null  object
 8   Image Link                   18539 non-null  object
 9   Age                          18539 non-null  int64
 10  Height(in cm)                18539 non-null  int64
 11  Weight(in kg)                18539 non-null  int64
 12  TotalStats                   18539 non-null  int64
 13  BaseStats                    18539 non-null  int64
 14  Club Name                    18539 non-null  object
 15  Wage(in Euro)                18539 non-null  int64
 16  Release Clause               18539 non-null  int64
 17  Club Position                18539 non-null  object
 18  Contract Until               18539 non-null  object
 19  Club Jersey Number           18539 non-null  object
 20  Joined On                    18539 non-null  int64
 21  On Loan                      18539 non-null  object
 22  Preferred Foot               18539 non-null  object
 23  Weak Foot Rating             18539 non-null  int64
 24  Skill Moves                  18539 non-null  int64
 25  International Reputation     18539 non-null  int64
 26  National Team Name           18539 non-null  object
 27  National Team Image Link     18539 non-null  object
 28  National Team Position       18539 non-null  object
 29  National Team Jersey Number  18539 non-null  object
 30  Attacking Work Rate          18539 non-null  object
 31  Defensive Work Rate          18539 non-null  object
 32  Pace Total                   18539 non-null  int64
 33  Shooting Total               18539 non-null  int64
 34  Passing Total                18539 non-null  int64
 35  Dribbling Total              18539 non-null  int64
 36  Defending Total              18539 non-null  int64
 37  Physicality Total            18539 non-null  int64
 38  Crossing                     18539 non-null  int64
 39  Finishing                    18539 non-null  int64
 40  Heading Accuracy             18539 non-null  int64
 41  Short Passing                18539 non-null  int64
 42  Volleys                      18539 non-null  int64
 43  Dribbling                    18539 non-null  int64
 44  Curve                        18539 non-null  int64
 45  Freekick Accuracy            18539 non-null  int64
 46  LongPassing                  18539 non-null  int64
 47  BallControl                  18539 non-null  int64
 48  Acceleration                 18539 non-null  int64
 49  Sprint Speed                 18539 non-null  int64
 50  Agility                      18539 non-null  int64
 51  Reactions                    18539 non-null  int64
 52  Balance                      18539 non-null  int64
 53  Shot Power                   18539 non-null  int64
 54  Jumping                      18539 non-null  int64
 55  Stamina                      18539 non-null  int64
 56  Strength                     18539 non-null  int64
 57  Long Shots                   18539 non-null  int64
 58  Aggression                   18539 non-null  int64
 59  Interceptions                18539 non-null  int64
 60  Positioning                  18539 non-null  int64
 61  Vision                       18539 non-null  int64
 62  Penalties                    18539 non-null  int64
 63  Composure                    18539 non-null  int64
 64  Marking                      18539 non-null  int64
 65  Standing Tackle              18539 non-null  int64
 66  Sliding Tackle               18539 non-null  int64
 67  Goalkeeper Diving            18539 non-null  int64
 68  Goalkeeper Handling          18539 non-null  int64
 69   GoalkeeperKicking           18539 non-null  int64
 70  Goalkeeper Positioning       18539 non-null  int64
 71  Goalkeeper Reflexes          18539 non-null  int64
 72  ST Rating                    18539 non-null  int64
 73  LW Rating                    18539 non-null  int64
 74  LF Rating                    18539 non-null  int64
 75  CF Rating                    18539 non-null  int64
 76  RF Rating                    18539 non-null  int64
 77  RW Rating                    18539 non-null  int64
 78  CAM Rating                   18539 non-null  int64
 79  LM Rating                    18539 non-null  int64
 80  CM Rating                    18539 non-null  int64
 81  RM Rating                    18539 non-null  int64
 82  LWB Rating                   18539 non-null  int64
 83  CDM Rating                   18539 non-null  int64
 84  RWB Rating                   18539 non-null  int64
 85  LB Rating                    18539 non-null  int64
 86  CB Rating                    18539 non-null  int64
 87  RB Rating                    18539 non-null  int64
 88  GK Rating                    18539 non-null  int64
dtypes: int64(71), object(18)
memory usage: 12.6+ MB

In [4]:
df.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Nationality', 'Image Link', 'Age',
       'Height(in cm)', 'Weight(in kg)', 'TotalStats', 'BaseStats',
       'Club Name', 'Wage(in Euro)', 'Release Clause', 'Club Position',
       'Contract Until', 'Club Jersey Number', 'Joined On', 'On Loan',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'National Team Name',
       'National Team Image Link', 'National Team Position',
       'National Team Jersey Number', 'Attacking Work Rate',
       'Defensive Work Rate', 'Pace Total', 'Shooting Total', 'Passing Total',
       'Dribbling Total', 'Defending Total', 'Physicality Total', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Dribbling', 'Curve', 'Freekick Accuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle',
       'Goalkeeper Diving', 'Goalkeeper Handling', ' GoalkeeperKicking',
       'Goalkeeper Positioning', 'Goalkeeper Reflexes', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating'],
      dtype='object')

In [6]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.fillna(df.mean(), inplace=True)

C:\Users\alberespi\AppData\Local\Temp\ipykernel_34028\3614303467.py:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18420 entries, 0 to 18538
Data columns (total 89 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Known As                     18420 non-null  object
 1   Full Name                    18420 non-null  object
 2   Overall                      18420 non-null  int64
 3   Potential                    18420 non-null  int64
 4   Value(in Euro)               18420 non-null  int64
 5   Positions Played             18420 non-null  object
 6   Best Position                18420 non-null  object
 7   Nationality                  18420 non-null  object
 8   Image Link                   18420 non-null  object
 9   Age                          18420 non-null  int64
 10  Height(in cm)                18420 non-null  int64
 11  Weight(in kg)                18420 non-null  int64
 12  TotalStats                   18420 non-null  int64
 13  BaseStats                    18420 non-null  int64
 14  Club Name                    18420 non-null  object
 15  Wage(in Euro)                18420 non-null  int64
 16  Release Clause               18420 non-null  int64
 17  Club Position                18420 non-null  object
 18  Contract Until               18420 non-null  object
 19  Club Jersey Number           18420 non-null  object
 20  Joined On                    18420 non-null  int64
 21  On Loan                      18420 non-null  object
 22  Preferred Foot               18420 non-null  object
 23  Weak Foot Rating             18420 non-null  int64
 24  Skill Moves                  18420 non-null  int64
 25  International Reputation     18420 non-null  int64
 26  National Team Name           18420 non-null  object
 27  National Team Image Link     18420 non-null  object
 28  National Team Position       18420 non-null  object
 29  National Team Jersey Number  18420 non-null  object
 30  Attacking Work Rate          18420 non-null  object
 31  Defensive Work Rate          18420 non-null  object
 32  Pace Total                   18420 non-null  int64
 33  Shooting Total               18420 non-null  int64
 34  Passing Total                18420 non-null  int64
 35  Dribbling Total              18420 non-null  int64
 36  Defending Total              18420 non-null  int64
 37  Physicality Total            18420 non-null  int64
 38  Crossing                     18420 non-null  int64
 39  Finishing                    18420 non-null  int64
 40  Heading Accuracy             18420 non-null  int64
 41  Short Passing                18420 non-null  int64
 42  Volleys                      18420 non-null  int64
 43  Dribbling                    18420 non-null  int64
 44  Curve                        18420 non-null  int64
 45  Freekick Accuracy            18420 non-null  int64
 46  LongPassing                  18420 non-null  int64
 47  BallControl                  18420 non-null  int64
 48  Acceleration                 18420 non-null  int64
 49  Sprint Speed                 18420 non-null  int64
 50  Agility                      18420 non-null  int64
 51  Reactions                    18420 non-null  int64
 52  Balance                      18420 non-null  int64
 53  Shot Power                   18420 non-null  int64
 54  Jumping                      18420 non-null  int64
 55  Stamina                      18420 non-null  int64
 56  Strength                     18420 non-null  int64
 57  Long Shots                   18420 non-null  int64
 58  Aggression                   18420 non-null  int64
 59  Interceptions                18420 non-null  int64
 60  Positioning                  18420 non-null  int64
 61  Vision                       18420 non-null  int64
 62  Penalties                    18420 non-null  int64
 63  Composure                    18420 non-null  int64
 64  Marking                      18420 non-null  int64
 65  Standing Tackle              18420 non-null  int64
 66  Sliding Tackle               18420 non-null  int64
 67  Goalkeeper Diving            18420 non-null  int64
 68  Goalkeeper Handling          18420 non-null  int64
 69   GoalkeeperKicking           18420 non-null  int64
 70  Goalkeeper Positioning       18420 non-null  int64
 71  Goalkeeper Reflexes          18420 non-null  int64
 72  ST Rating                    18420 non-null  int64
 73  LW Rating                    18420 non-null  int64
 74  LF Rating                    18420 non-null  int64
 75  CF Rating                    18420 non-null  int64
 76  RF Rating                    18420 non-null  int64
 77  RW Rating                    18420 non-null  int64
 78  CAM Rating                   18420 non-null  int64
 79  LM Rating                    18420 non-null  int64
 80  CM Rating                    18420 non-null  int64
 81  RM Rating                    18420 non-null  int64
 82  LWB Rating                   18420 non-null  int64
 83  CDM Rating                   18420 non-null  int64
 84  RWB Rating                   18420 non-null  int64
 85  LB Rating                    18420 non-null  int64
 86  CB Rating                    18420 non-null  int64
 87  RB Rating                    18420 non-null  int64
 88  GK Rating                    18420 non-null  int64
dtypes: int64(71), object(18)
memory usage: 12.6+ MB

In [8]:
df.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Positions Played', 'Best Position', 'Nationality', 'Image Link', 'Age',
       'Height(in cm)', 'Weight(in kg)', 'TotalStats', 'BaseStats',
       'Club Name', 'Wage(in Euro)', 'Release Clause', 'Club Position',
       'Contract Until', 'Club Jersey Number', 'Joined On', 'On Loan',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'National Team Name',
       'National Team Image Link', 'National Team Position',
       'National Team Jersey Number', 'Attacking Work Rate',
       'Defensive Work Rate', 'Pace Total', 'Shooting Total', 'Passing Total',
       'Dribbling Total', 'Defending Total', 'Physicality Total', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Dribbling', 'Curve', 'Freekick Accuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle',
       'Goalkeeper Diving', 'Goalkeeper Handling', ' GoalkeeperKicking',
       'Goalkeeper Positioning', 'Goalkeeper Reflexes', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating'],
      dtype='object')

In [9]:
df.drop(columns={'Positions Played', 'Image Link', 'Release Clause', 'Club Position',
                 'Contract Until', 'Club Jersey Number', 'Joined On', 'On Loan', 
                 'National Team Name', 'National Team Image Link', 'National Team Position', 
                 'National Team Jersey Number'}, inplace=True)

In [10]:
df.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Best Position', 'Nationality', 'Age', 'Height(in cm)', 'Weight(in kg)',
       'TotalStats', 'BaseStats', 'Club Name', 'Wage(in Euro)',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'Attacking Work Rate',
       'Defensive Work Rate', 'Pace Total', 'Shooting Total', 'Passing Total',
       'Dribbling Total', 'Defending Total', 'Physicality Total', 'Crossing',
       'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Dribbling', 'Curve', 'Freekick Accuracy', 'LongPassing', 'BallControl',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'Standing Tackle', 'Sliding Tackle',
       'Goalkeeper Diving', 'Goalkeeper Handling', ' GoalkeeperKicking',
       'Goalkeeper Positioning', 'Goalkeeper Reflexes', 'ST Rating',
       'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating', 'RW Rating',
       'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating', 'LWB Rating',
       'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating', 'RB Rating',
       'GK Rating'],
      dtype='object')

In [12]:
non_numeric_columns = df.select_dtypes(exclude='number').columns
print(non_numeric_columns)

Index(['Known As', 'Full Name', 'Best Position', 'Nationality', 'Club Name',
       'Preferred Foot', 'Attacking Work Rate', 'Defensive Work Rate'],
      dtype='object')

In [13]:
unique_values_pf = df['Preferred Foot'].unique()
print(unique_values_pf)

['Left' 'Right']

In [14]:
df["Preferred Foot"].replace({"Left": 0, "Right": 1}, inplace=True)

In [15]:
unique_values_pf = df['Preferred Foot'].unique()
print(unique_values_pf)

[0 1]

In [16]:
df_encoded = pd.get_dummies(df, columns=["Attacking Work Rate", "Defensive Work Rate"])
df_encoded

,Known As,Full Name,Overall,Potential,Value(in Euro),Best Position,Nationality,Age,Height(in cm),Weight(in kg),...,LB Rating,CB Rating,RB Rating,GK Rating,Attacking Work Rate_High,Attacking Work Rate_Low,Attacking Work Rate_Medium,Defensive Work Rate_High,Defensive Work Rate_Low,Defensive Work Rate_Medium
0,L. Messi,Lionel Messi,91,91,54000000,CAM,Argentina,35,169,67,...,62,53,62,22,0,1,0,0,1,0
1,K. Benzema,Karim Benzema,91,91,64000000,CF,France,34,185,81,...,63,58,63,21,0,0,1,0,0,1
2,R. Lewandowski,Robert Lewandowski,91,91,84000000,ST,Poland,33,185,81,...,64,63,64,22,1,0,0,0,0,1
3,K. De Bruyne,Kevin De Bruyne,91,91,107500000,CM,Belgium,31,181,70,...,78,72,78,24,1,0,0,1,0,0
4,K. Mbappé,Kylian Mbappé,91,95,190500000,ST,France,23,182,73,...,66,57,66,21,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,D. Collins,Darren Collins,47,56,110000,CAM,Republic of Ireland,21,174,68,...,40,36,40,15,0,0,1,0,0,1
18535,Yang Dejiang,Dejiang Yang,47,57,90000,CDM,China PR,17,175,60,...,49,49,49,15,0,0,1,0,0,1
18536,L. Mullan,Liam Mullan,47,67,130000,RM,Northern Ireland,18,170,65,...,46,42,46,17,1,0,0,0,0,1
18537,D. McCallion,Daithí McCallion,47,61,100000,CB,Republic of Ireland,17,178,65,...,47,49,47,15,0,0,1,0,0,1
18538,N. Rabha,Nabin Rabha,47,50,60000,LB,India,25,176,66,...,47,47,47,19,0,0,1,0,0,1

In [17]:
df_encoded.columns

Index(['Known As', 'Full Name', 'Overall', 'Potential', 'Value(in Euro)',
       'Best Position', 'Nationality', 'Age', 'Height(in cm)', 'Weight(in kg)',
       'TotalStats', 'BaseStats', 'Club Name', 'Wage(in Euro)',
       'Preferred Foot', 'Weak Foot Rating', 'Skill Moves',
       'International Reputation', 'Pace Total', 'Shooting Total',
       'Passing Total', 'Dribbling Total', 'Defending Total',
       'Physicality Total', 'Crossing', 'Finishing', 'Heading Accuracy',
       'Short Passing', 'Volleys', 'Dribbling', 'Curve', 'Freekick Accuracy',
       'LongPassing', 'BallControl', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Shot Power', 'Jumping', 'Stamina', 'Strength',
       'Long Shots', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeper Diving', 'Goalkeeper Handling',
       ' GoalkeeperKicking', 'Goalkeeper Positioning', 'Goalkeeper Reflexes',
       'ST Rating', 'LW Rating', 'LF Rating', 'CF Rating', 'RF Rating',
       'RW Rating', 'CAM Rating', 'LM Rating', 'CM Rating', 'RM Rating',
       'LWB Rating', 'CDM Rating', 'RWB Rating', 'LB Rating', 'CB Rating',
       'RB Rating', 'GK Rating', 'Attacking Work Rate_High',
       'Attacking Work Rate_Low', 'Attacking Work Rate_Medium',
       'Defensive Work Rate_High', 'Defensive Work Rate_Low',
       'Defensive Work Rate_Medium'],
      dtype='object')

In [20]:
df_categorical = df_encoded.select_dtypes(exclude=['number'])
df_numeric = df_encoded.select_dtypes(include='number')

In [21]:
df_categorical

,Known As,Full Name,Best Position,Nationality,Club Name
0,L. Messi,Lionel Messi,CAM,Argentina,Paris Saint-Germain
1,K. Benzema,Karim Benzema,CF,France,Real Madrid CF
2,R. Lewandowski,Robert Lewandowski,ST,Poland,FC Barcelona
3,K. De Bruyne,Kevin De Bruyne,CM,Belgium,Manchester City
4,K. Mbappé,Kylian Mbappé,ST,France,Paris Saint-Germain
...,...,...,...,...,...
18534,D. Collins,Darren Collins,CAM,Republic of Ireland,Sligo Rovers
18535,Yang Dejiang,Dejiang Yang,CDM,China PR,Guangzhou FC
18536,L. Mullan,Liam Mullan,RM,Northern Ireland,Derry City
18537,D. McCallion,Daithí McCallion,CB,Republic of Ireland,Derry City
18538,N. Rabha,Nabin Rabha,LB,India,NorthEast United FC

In [22]:
df_numeric

,Overall,Potential,Value(in Euro),Age,Height(in cm),Weight(in kg),TotalStats,BaseStats,Wage(in Euro),Preferred Foot,...,LB Rating,CB Rating,RB Rating,GK Rating,Attacking Work Rate_High,Attacking Work Rate_Low,Attacking Work Rate_Medium,Defensive Work Rate_High,Defensive Work Rate_Low,Defensive Work Rate_Medium
0,91,91,54000000,35,169,67,2190,452,195000,0,...,62,53,62,22,0,1,0,0,1,0
1,91,91,64000000,34,185,81,2147,455,450000,1,...,63,58,63,21,0,0,1,0,0,1
2,91,91,84000000,33,185,81,2205,458,420000,1,...,64,63,64,22,1,0,0,0,0,1
3,91,91,107500000,31,181,70,2303,483,350000,1,...,78,72,78,24,1,0,0,1,0,0
4,91,95,190500000,23,182,73,2177,470,230000,1,...,66,57,66,21,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18534,47,56,110000,21,174,68,1287,274,500,1,...,40,36,40,15,0,0,1,0,0,1
18535,47,57,90000,17,175,60,1289,267,500,1,...,49,49,49,15,0,0,1,0,0,1
18536,47,67,130000,18,170,65,1333,277,500,1,...,46,42,46,17,1,0,0,0,0,1
18537,47,61,100000,17,178,65,1113,226,500,1,...,47,49,47,15,0,0,1,0,0,1
18538,47,50,60000,25,176,66,1277,269,500,0,...,47,47,47,19,0,0,1,0,0,1

In [24]:
df_categorical.to_csv('./data/fifa23_cat_clean.csv', index=False)
df_numeric.to_csv('./data/fifa23_num_clean.csv', index=False)